### ISSUE TITLE
Version 0.0.1 or 1.0.0 ?

### ISSUE THREAD

**Issue by wallymathieu** [fsprojects/SyntacticVersioning#14]
### Description

I accidentally uploaded two NuGet packages while pushing to NuGet. The question is if NuGet will remove the 1.0.0 version or if we should start with version 1.0.0 ?

**Comment by wallymathieu** [comment]
Looks like there are already downloads on 1.0.0, the version information about it is wrong, so next version should probably be 1.0.1

**Comment by wallymathieu** [comment]
The 1.0.0 version has been taken down by nuget, so yay! Mistake corrected. We can continue with publishing small number versions.

**Comment by ghost** [comment]
I usually start my projects with the following version number: `0.11.0` (the eleventh letter in the Greek alphabet :+1: )
