### ISSUE TITLE
.NET Core support 

### ISSUE THREAD

**Issue by nalvid** [fsprojects/SyntacticVersioning#18]
Is it possible to use the library with  .NET Core? Thanks!

**Comment by wallymathieu** [comment]
Hi! I'm looking into porting it to .net core.
Though, you can use the tool to diff .net core assemblies even though it's a bit of a pain (when you have assemblies that references other assemblies in other nuget packages).

**Comment by wallymathieu** [comment]
So yes, it's possible. Though we are looking at making it better.

**Comment by wallymathieu** [comment]
@uetoyo Could you test this with some .net core assemblies?
