### ISSUE TITLE
Order of enum members

### ISSUE THREAD

**Issue by wallymathieu** [fsprojects/SyntacticVersioning#3]
### Description

Is the order of enum members a part of an API? For instance if you have something like:
```f#
type Enum = | Foo = 0 | Bar = 2 | Qux = 5 | Baz = 3  
```
that get changed to
```f#
type Enum = | Foo = 0 | Bar = 2 | Baz = 3 | Qux = 5  
```
Is that considered a change? 

While for instance this change:
```f#
type Enum = | Baz = 3 | Foo = 0 | Bar = 2 | Qux = 5 
```
that get changed to
```f#
type Enum = | Foo = 0 | Bar = 2 | Baz = 3 | Qux = 5  
```
would change the meaning of
```c#
T temp = default(T);
```

**Comment by ghost** [comment]
The main reason I order the `enum` and `Union` is to avoid if somebody moves up and down of cases to be marked as a `major` change.

I think that's how it works :+1: 

> Note: If you change the value of an `enum` that IS a `major` change

**Comment by wallymathieu** [comment]
The enum members are not ordered in the output, if you look at the test [Enum2.txt](https://github.com/fsprojects/SyntacticVersioning/blob/master/tests/ExampleProjects/src/Enum2.txt).
But yes, a change of value of an ```enum``` is always a ```major``` change.

**Comment by ghost** [comment]
Hmmmm, don't I order `Union Types`? Or at least I thought about it but then again, you changing the order in the code API, will not impact users code as `pattern-match` don't really care about order.

**Comment by ghost** [comment]
Maybe there is an ordering of ```Union Types```, but there is separate code for ```Enum```

**Comment by ghost** [comment]
Yes, I know. `Union Types` can have different `types` or none, while `Enums` always are of type `int`

**Comment by wallymathieu** [comment]
I'm thinking about moving Enum members to be part of the Members structure. I.e. change the format a bit. Decomposing the enum members to be separate Members has an implication on how we see them (if reordering of them is significant or not). I think that it sounds like we don't care about the order of enum members.

**Comment by ghost** [comment]
Hmmm, I was pretty sure that I was ordering `(key,value)` for `enum`s:

https://github.com/spisemisu/SpiseMisu.SemanticVersioning/blob/sync/src/SpiseMisu.SemanticVersioning/Versioning.fs#L54

The question is, why is it not sorted :+1:

**Comment by ghost** [comment]
And the same goes for `Union types`:

https://github.com/spisemisu/SpiseMisu.SemanticVersioning/blob/sync/src/SpiseMisu.SemanticVersioning/Versioning.fs#L86

Spooky

**Comment by ghost** [comment]
Indeed! Good to know!

**Comment by wallymathieu** [comment]
So probably that it has been lost in translation.
