### ISSUE TITLE
consider distributing as a dotnet-cli global tool

### ISSUE THREAD

**Issue by baronfel** [fsprojects/SyntacticVersioning#32]
### Description

First off, this tool is great and I have used it several times to solve problems related to API surface area.

I think usability-wise it would be excellent if the current binary was also packaged/shipped as a dotnet sdk global/local tool, so that users could do something like

```shell
dotnet tool install synver -g
synver bump .
// or 
synver diff dllA dllB --format json
```

etc.  This would also allow for users adding the tool to their tool manifest so it's restored alongside other packages.

I'd be willing to do this work if you like the suggestion, but it might be a bit because I'm prepping for OpenF# at the moment.

**Comment by wallymathieu** [comment]
Yes! That would be awesome.

**Comment by wallymathieu** [comment]
From what I can see in the code, it looks like `synver` deliverable is supposed to be a tool package. I've marked this issue as a bug.

**Comment by baronfel** [comment]
in that case it should be as easy as adding `<PackAsTool>true</PackAsTool>` to the project file and re-publishing.

I took an actual look at the cli project and it already does all the things I wanted, so that one flag should close this out.

**Comment by wallymathieu** [comment]
Do you want to do the honours?

**Comment by baronfel** [comment]
after looking into it, to add dotnet-sdk-tool support we'd have to drop support the .net framework exe.  I personally think that's acceptable: the library can target netstandard2.0, and everyone should be on at least net462 IMO.

**Comment by baronfel** [comment]
it works!

```shell
➜  SynVer git:(global-tool) ✗ dotnet tool install -g --add-source bin/Debug synver    
You can invoke the tool using the following command: synver
Tool 'synver' (version '0.0.8') was successfully installed.
➜  SynVer git:(global-tool) ✗ synver
USAGE: synver.exe [--help] [--surface-of <path>] [--decompile] [--output <path>] [--diff <source> <target>] [--bump <version> <source> <target>]
                  [--magnitude <source> <target>]

OPTIONS:

    --surface-of <path>   Get the public api surface of the .net binary as lson
    --decompile           Decompile instead of using reflection
    --output <path>       Send output to file
    --diff <source> <target>
                          Get the difference between two .net binaries
    --bump <version> <source> <target>
                          Get the next version based on the difference between two .net binaries
    --magnitude <source> <target>
                          Get the magnitude of the difference between two .net binaries
    --help                display this list of options.
```

so if those changes are acceptable to you I'll send up the MR.

**Comment by wallymathieu** [comment]
Sounds great 😄

**Comment by baronfel** [comment]
This has turned into a whole thing because the version of fake the build script is on can't find some of the newer sdk whizbang gizmos. So now I'm wrestling with a fake upgrade as well. Made more complicated by the tenuous state of fsharp.formatting and the fsc/csc compilation helpers.

**Comment by wallymathieu** [comment]
Dang, that's unfortunate. Anything I can help out with?

**Comment by baronfel** [comment]
Opened #33 to show current progress/contain the discussion.

**Comment by wallymathieu** [comment]
I've merged the PR and published new versions on nuget.

**Comment by wallymathieu** [comment]
Thanks @baronfel for the help! 😃

**Comment by baronfel** [comment]
Done!
