### ISSUE TITLE
Fix build on Windows

### ISSUE THREAD

**Issue by wallymathieu** [fsprojects/SyntacticVersioning#35]
- Issues building on Appveyor: `Start of process '/c/Program Files/dotnet/dotnet' failed`
- Issues building on Windows 10 cmd prompt: Could not find executable which ...

**Comment by tomakita** [comment]
I have this working locally on Windows, and will submit a PR soon.

**Comment by tomakita** [comment]
PR has been submitted!

**Comment by wallymathieu** [comment]
Many thanks for the help! 😄
