### ISSUE TITLE
Dependency on chiron

### ISSUE THREAD

**Issue by wallymathieu** [fsprojects/SyntacticVersioning#5]
### Description

We will take a dependency on [chiron](https://github.com/xyncro/chiron) 

## Goals 
- [x] Be able to serialise an assembly surface area to some simple format 
- [ ] Have chiron (or other simple tool) as a file reference and that module should be ```internal```.
- [ ] Be able to diff an assembly and serialised in some simple format

**Comment by ghost** [comment]
Why do we need serialization for? (if I might ask)

**Comment by wallymathieu** [comment]
In order to compare assemblies without having them always loaded. Perhaps enable expecto to use a persisted format to diff the types against.

**Comment by ghost** [comment]
So you will create somekind of `bump` to `json` (containing an an SHA-256 checksum of the `.dll` file) that will allow you to compare to assemblies without having to `reflect` them? Sound reasonable :+1: 

This way, you can download an assembly, checksum it against you local `json` serialization, if they match, you can just `diff` your `json` files.

**Comment by wallymathieu** [comment]
I like the idea about using checksum! 👍

**Comment by haf** [comment]
You can add a file reference too and make the module `internal`.

**Comment by wallymathieu** [comment]
Do you have any example of  file reference of Chiron?

**Comment by ghost** [comment]
@wallymathieu in my previous job I had to make the `hash` on the source files:

https://github.com/delegateas/Delegate.Daxif/blob/master/src/Delegate.Daxif/HelperModules/PluginsHelper.fs#L505-L509

Because compiling is non deterministic (you will never get the same `bits` out twice due to compiler optimizations). Therefore, if any built is involved, we will have to do the same here.

**Comment by wallymathieu** [comment]
Perhaps the best way is to avoid having the hash to begin with, and then do as in the PluginsHelper ?

**Comment by ghost** [comment]
Well we stored the hash in the target system.

We calculated locally the `hash` based on the source code, but when we compared to the uploaded assembly, we needed to save the `hash` code remotely:

https://github.com/delegateas/Delegate.Daxif/blob/master/src/Delegate.Daxif/HelperModules/PluginsHelper.fs#L634

**Comment by wallymathieu** [comment]
Computing a ```hash``` for an assembly based on the source is a lot of work. We would need to parse msbuild project files et.c. if we want to be correct (since the source files can be outside of the project home). The easiest starting point is to always generate ```Patch``` if the surface area looks the same.

**Comment by ghost** [comment]
If you look into my approach, when I run `bump` and if the there is no `major` or `minor` changes. I just increment `patch`.

I think this was one of the differences between our solutions. I don't handle changes at all (while you do), I only look for addition or deletion.

**Comment by wallymathieu** [comment]
Yes, the code I had for comparison was a port of parts of the Haskell Elm code. I think some things where very different since the concepts are fewer in that code, since it had a simpler type system to deal with. Right now in SyntacticVersioning, the Compare part is very much your code. I'm going to add tests of getting the comparison as an object as well (but later on).

**Comment by ghost** [comment]
My assumption was just that if you are running this (`bump`), well you might have been doing some changes (`patching`) or just a build server running after some code change. Either way, it shouldn't have no impact on the consumers of the `API` therefore it should just be a `patch`. Very simple and seems to do the job (always use `KISS` when it's possible) :+1:

**Comment by wallymathieu** [comment]
Indeed!
